steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - docker/dockerfile
      - -t
      - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}
      - -t
      - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest
      - .

images:
  - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${COMMIT_SHA}
  - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest

substitutions:
  _AR_HOSTNAME: us-docker.pkg.dev
  _AR_REPOSITORY: regifter
  _SERVICE_NAME: webapp

options:
  logging: CLOUD_LOGGING_ONLY
